import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../../styles/Home.module.css'
import Slider from 'react-slick'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'

// image
import battery from '../public/battery.png'
import laptopImage from '../../../public/laptop-unsplash.jpg'
import laptopAnna from '../../../public/pexels-anna-shvets.jpg'
import laptopTima from '../../../public/pexels-tima.jpg'
import imageadds from '../../../public/imageAdds.jpg'
import imageadds2 from '../../../public/imageAdds2.jpg'
import imageadds3 from '../../../public/imageAdds3.jpg'

import { CardStatistic, CardBenefit, Card } from '../../components'

import {
  FaSearch,
  FaVideo,
  FaUser,
  FaRegClock,
  FaBookOpen,
} from 'react-icons/fa'
import {
  AiFillVideoCamera,
  AiOutlineArrowRight,
  AiOutlineDingding,
  AiOutlineFieldTime,
  AiOutlineKey,
  AiOutlinePieChart,
  AiOutlineTeam,
  AiOutlineUnorderedList,
} from 'react-icons/ai'

export default function Home() {
  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    // slidesToShow: 1,
    slidesToShow: 3,
    // slidesToScroll: 1,
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='container mx-auto'>
        <nav
          className='flex flex-row justify-between
      items-center h-20'>
          <Link href='https://nextjs.org/docs/api-reference/next/link'>
            <a className='flex flex-row items-center'>
              <div className='mr-4'>
                <Image
                  src='https://avatars.githubusercontent.com/u/22560475?v=4'
                  height={45}
                  width={45}
                  alt='Dari Dasar'
                />
              </div>
              <div className='font-medium'>daridasar.com</div>
            </a>
          </Link>
          <div>
            <button className='mx-4 hover:bg-blue-50 hover:text-blue-500 py-2 px-5 rounded-full transition duration-200 text-gray-500'>
              Kelas
            </button>
            <button className='mx-4 hover:bg-blue-50 hover:text-blue-500 py-2 px-5 rounded-full transition duration-200 text-gray-500'>
              Buku
            </button>
            <button className='mx-4 hover:bg-blue-50 hover:text-blue-500 py-2 px-5 rounded-full transition duration-200 text-gray-500'>
              Blog
            </button>
          </div>
          <div>
            <button className='mx-4 hover:bg-blue-50 hover:text-blue-500 py-2 px-5 rounded-full transition duration-200 text-gray-500'>
              Login
            </button>
            <button className='bg-blue-500 py-2 px-5 rounded-full text-white hover:bg-blue-300'>
              Get Started
            </button>
          </div>
        </nav>
      </div>
      <main className={styles.main}>
        {/* Navbar */}
        <div className='flex flex-col items-center h-96 justify-center'>
          <h1 className={styles.title}>Learn Programming from scratch</h1>
          <p className='my-4 w-96 text-2xl text-center'>
            Never too late to learn anything
          </p>

          <div className='flex justify-center items-center mt-4 '>
            <input
              type='text'
              name='search'
              id='hero_search'
              placeholder='Search...'
              className='rounded-sm p-2 bg-gray-100 focus:outline-none w-25'
            />

            <button className='flex flex-row bg-gray-100 p-3 hover:bg-gray-300'>
              <FaSearch className='text-gray-500' />
            </button>
          </div>
        </div>
        {/* #region Text Welcome */}
        <div className='container mx-auto'>
          <div className='flex flex-row justify-around py-10'>
            <CardStatistic
              title='40+'
              description='Study with 40 course available'
              icon={<FaBookOpen size='40' className='mb-4 text-black' />}
            />
            <CardStatistic
              title='2000+'
              description='Have more than 2000 vidos'
              icon={<FaVideo size='40' className='mb-4 text-black' />}
            />
            <CardStatistic
              title='15.000+'
              description='15.000 watch hour'
              icon={<FaRegClock size='40' className='mb-4 text-black' />}
            />
            <CardStatistic
              title='1.000.000+'
              description='Join with more than 1.000.000+ Member'
              icon={<FaUser size='40' className='mb-4 text-black' />}
            />
          </div>
        </div>

        {/* Profit */}
        <div className='bg-gray-100 py-12'>
          <div className='container flex mx-auto flex-row justify-center items-center'>
            <div className='flex-1'>
              <div className='text-3xl font-semibold'>
                Got what you want to Get
              </div>
              <div className='mt-4'>
                What is the advantages of studying at the daridasar.com service
                ?
              </div>
            </div>
            <div className='flex-1 grid grid-cols-3 gap-4'>
              <CardBenefit
                title='Time'
                description=' Kamu bebas menentukan waktu yakin belajar kapan saja '
                icon={<FaUser size='20' className='text-gray-400' />}
              />
              <CardBenefit
                title='Material'
                description='Memahami materi dengan detail'
                icon={<AiOutlinePieChart size='20' className='text-gray-400' />}
              />
              <CardBenefit
                title='Trainer'
                description=' Belajar bersama praktisi dibidangnya '
                icon={<AiOutlineTeam size='20' className='text-gray-400' />}
              />
              <CardBenefit
                title='Video'
                description=' Belajar menggunakan video dengan kualitas HD '
                icon={<AiFillVideoCamera size='20' className='text-gray-400' />}
              />
              <CardBenefit
                title='Case Studi'
                description='
                  Belajar dengan studi kasus
                '
                icon={<AiOutlineKey size='20' className='text-gray-400' />}
              />
              <CardBenefit
                title='Dari Dasar'
                description='Materi belajar dimulai dari dasar.'
                icon={
                  <AiOutlineUnorderedList size='20' className='text-gray-400' />
                }
              />
              <CardBenefit
                title='Check'
                description='
                  Memastikan kamu mengerti dengan apa yang kamu pelajari
                '
                icon={<AiOutlineDingding size='20' className='text-gray-400' />}
              />
            </div>
          </div>
        </div>

        <div className='text-center my-8'>
          <div className='text-3xl font-bold'>Start together daridasar.com</div>
          <div>
            Platform belajar yang dapat membantu belajar apapun dari dasar
          </div>
        </div>

        <div className='container mx-auto my-8'>
          <div className='flex flex-row justify-between my-4 items-center'>
            <div className='uppercase text-gray-800 text-lg'>Course</div>
            <a href='/blog' className='text-gray-500 text-sm'>
              <div className='flex justify-center items-center'>
                Read More <AiOutlineArrowRight />
              </div>
            </a>
          </div>
          <Slider {...settings}>
            <Card
              img={laptopImage}
              title='Laptop image'
              price='Rp 200.000,-'
              author='Dev ed'
            />
            <Card
              img={laptopAnna}
              title='Laptop image'
              price='Rp 200.000,-'
              author='Dev ed'
            />
            <Card
              img={laptopTima}
              title='Laptop image'
              price='Rp 200.000,-'
              author='Dev ed'
            />
            <Card
              img={imageadds}
              title='Laptop image'
              price='Rp 200.000,-'
              author='Dev ed'
            />
            <Card
              img={imageadds2}
              title='Laptop image'
              price='Rp 200.000,-'
              author='Dev ed'
            />
            <Card
              img={imageadds3}
              title='Laptop image'
              price='Rp 120.000,-'
              author='Dev ed'
            />
          </Slider>
        </div>

        <div className='bg-gray-100 py-12'>
          <div className='text-center'>
            <div className='text-4xl font-bold'>Pricing</div>
            <div>Upgrade to Premium and get even more.</div>
          </div>
          <div className='flex flex-row justify-center bg-opacity-50 my-8'>
            <div className='flex flex-col justify-between items-center shadow-md bg-white mx-2 p-6 rounded-lg w-72'>
              <div className='text-gray-800 text-3xl font-medium'>Free</div>
              <div className='text-gray-500 my-8 px-2'>
                daridasar gives you 100s of course, unlimited exercise & top
                grade ebook FREE.
              </div>
              <div>
                <div className='text-xs'>Free</div>
                <div className='text-gray-800 text-3xl font-medium text-center'>
                  Rp. 0,-
                </div>
              </div>
            </div>
            <div className='flex flex-col justify-between items-center shadow-md bg-white mx-2 p-6 rounded-lg w-72'>
              <div className='text-gray-800 text-3xl font-medium text-center'>
                Premium
              </div>
              <div className='text-gray-500 my-8 px-2'>
                You can buy various classes with a one-time payment system, can
                access forever to the classes you buy
              </div>
              <div>
                <div className='text-xs'>Free</div>
                <div className='text-gray-800 text-3xl font-medium'>
                  Rp. 150.000,-
                </div>
              </div>
            </div>
            <div className='flex flex-col justify-between items-center shadow-md bg-white mx-2 p-6 rounded-lg w-72'>
              <div className='text-gray-800 text-3xl font-medium text-center'>
                VIP First <br /> ( Priority Support)
              </div>
              <div className='text-gray-500 my-8 px-2'>
                daridasar gives you 100s of course, unlimited exercise & top
                grade ebook FREE.
              </div>
              <div>
                <div className='text-xs'>Free</div>
                <div className='text-gray-800 text-3xl font-medium'>
                  Rp. 0,-
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className='flex flex-row'>
          <div className='flex-1 flex'>
            <img
              src='https://static.wixstatic.com/media/1f4e5a_4a9994cf7cbe44aba5deba197d95f827~mv2_d_1924_1924_s_2.jpg/v1/fill/w_667,h_961,al_c,q_85,usm_0.66_1.00_0.01/1f4e5a_4a9994cf7cbe44aba5deba197d95f827~mv2_d_1924_1924_s_2.webp'
              alt='Stock Image'
              className='2xl:hidden'
            />
            <img
              src='https://static.wixstatic.com/media/1f4e5a_4a9994cf7cbe44aba5deba197d95f827~mv2_d_1924_1924_s_2.jpg/v1/fill/w_1924,h_692,al_c,q_85/1f4e5a_4a9994cf7cbe44aba5deba197d95f827~mv2_d_1924_1924_s_2.webp'
              alt='Stock image'
              className='img2xl'
            />
          </div>

          <div className='flex-1 flex flex-col justify-center items-center max-w-full'>
            <div className='max-w-md'>
              <div className='text-5xl'>
                Manage, Promote and Grow What Your learn Online
              </div>
              <div className='text-lg mt-10'>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Assumenda inventore rerum nemo vero, iusto corporis illum sed
                necessitatibus itaque non!
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <div className='flex flex-row justify-center items-center'>
          ©&nbsp;
          <a href='/' className='text-blue-400'>
            daridasar.com
          </a>
          &nbsp;by&nbsp;
          <a href='/' className='text-blue-400'>
            Zealous
          </a>
          &nbsp; 2020 - now()
        </div>
      </footer>
    </div>
  )
}
